server:
  port: 8080
spring:
  application:
    name: fps-bus-ms-process-kpi
  profiles:
    active: ${PROFILE:local}
  main:
    web-application-type: reactive
  data:
    mongodb:
      uri: 
      database: FapeConnect
logging:
  config: classpath:logging/logback.xml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
validation-custom:
  app-id-flag: 0
  app-id: ZnBzLWJ1cy1tcy1wcm9jZXNzLWtwaQ==
kpi:
  batch:
    size: 3  # Número de días a procesar por lote
    delay: 500  # Delay entre lotes en milisegundos